@address = 127.0.0.1:3000

#### POST create characters
#POST http://{{address}}/characters
#Content-Type: application/json
#
#{
#  "name": "Harry Bosch"
#}

### GET characters by name
GET http://{{address}}/characters?name=Harry Bosch
Content-Type: application/json

> {% client.global.set("characterID", response.body.id); %}


### POST character add book
POST http://{{address}}/characters/{{characterID}}/books
Content-Type: application/json

{
  "bookTitles": [
    "The Black Echo",
    "The Black Ice",
    "The Concrete Blonde",
    "The Last Coyote",
    "Trunk Music",
    "Angels Flight",
    "A Darkness More Than Night",
    "City Of Bones",
    "Lost Light"
  ]
}