@address = 127.0.0.1:3000

#### POST create Harry Bosch
POST http://{{address}}/characters
Content-Type: application/json

{
  "name": "Harry Bosch",
  "actors": [
    {
      "name": "Titus Welliver",
      "imdb": "https://www.imdb.com/name/nm0920038"
    }
  ],
  "bookTitles": [
    "The Black Echo",
    "The Black Ice",
    "The Concrete Blonde",
    "The Last Coyote",
    "Trunk Music",
    "Angels Flight",
    "A Darkness More Than Night",
    "City Of Bones",
    "Lost Light",
    "The Narrows",
    "The Closers",
    "Echo Park",
    "The Overlook",
    "Nine Dragons",
    "The Drop",
    "The Black Box",
    "The Burning Room",
    "The Crossing",
    "The Wrong Side Of Goodbye",
    "Two Kinds Of Truth",
    "Dark Sacred Night",
    "The Night Fire",
    "The Dark Hours",
    "Desert Star",
    "The Waiting",
    "The Brass Verdict",
    "The Reversal",
    "The Law Of Innocence",
    "Resurrection Walk",
    "The Fifth Witness",
    "The Gods of Guilt"
  ]
}

### POST create Mickey Haller
POST http://{{address}}/characters
Content-Type: application/json

{
  "name": "Mickey Haller",
  "actors": [
    {
      "name":"Manuel Garcia-Rulfo",
      "imdb":  "https://www.imdb.com/pt/name/nm2636310"
    },
    {
      "name":"Matthew McConaughey",
      "imdb":  "https://www.imdb.com/name/nm0000190"
    }
  ],
  "bookTitles": [
    "The Lincoln Lawyer",
    "The Brass Verdict",
    "The Reversal",
    "The Fifth Witness",
    "The Gods of Guilt",
    "The Law Of Innocence",
    "Resurrection Walk",
    "The Proving Ground",
    "Nine Dragons",
    "The Crossing",
    "The Wrong Side Of Goodbye",
    "Two Kinds Of Truth",
    "The Night Fire",
    "Desert Star"
  ]
}

### POST create Renée Ballard
POST http://{{address}}/characters
Content-Type: application/json

{
  "name": "Renée Ballard",
  "actors": [
    {
      "name":"Maggie Q",
      "imdb":  "https://www.imdb.com/name/nm0702572"
    }
  ],
  "bookTitles": [
    "The Late Show",
    "Dark Sacred Night",
    "The Night Fire",
    "The Dark Hours",
    "Desert Star",
    "The Waiting",
    "Resurrection Walk"
  ]
}

### POST create Jack McEvoy
POST http://{{address}}/characters
Content-Type: application/json

{
  "name": "Jack McEvoy",
  "bookTitles": [
    "The Poet",
    "The Scarecrow",
    "Fair Warning",
    "The Proving Ground",
    "A Darkness More Than Night",
    "The Brass Verdict"
  ]
}

### POST create Detective Stilwell
POST http://{{address}}/characters
Content-Type: application/json

{
  "name": "Detective Stilwell",
  "bookTitles": [
    "Nightshade"
  ]
}

### POST create Rachel Walling
POST http://{{address}}/characters
Content-Type: application/json

{
  "name": "Rachel Walling",
  "actors": [
    {
      "name": "Julie St. Claire",
      "imdb": "https://www.imdb.com/name/nm0002930"
    }
  ],
  "bookTitles": [
    "The Poet",
    "The Narrows",
    "Echo Park",
    "The Overlook",
    "The Scarecrow",
    "Fair Warning",
    "The Reversal",
    "The Black Box",
    "The Burning Room"
  ]
}

#### POST create Terry McCaleb
POST http://{{address}}/characters
Content-Type: application/json

{
  "name": "Terry McCaleb",
  "actors": [
    {
      "name": "Clint Eastwood",
      "imdb": "https://www.imdb.com/name/nm0000142"
    }
  ],
  "bookTitles": [
    "Blood Work",
    "A Darkness More Than Night",
    "The Narrows"
  ]
}

### POST create Cassie Black
POST http://{{address}}/characters
Content-Type: application/json

{
  "name": "Cassie Black",
  "bookTitles": [
    "Void Moon",
    "The Narrows"
  ]
}

### POST create Henry Pierce
POST http://{{address}}/characters
Content-Type: application/json

{
  "name": "Henry Pierce",
  "bookTitles": [
    "Chasing The Dime"
  ]
}

### POST create Eleanor Wish
POST http://{{address}}/characters
Content-Type: application/json

{
  "name": "Eleanor Wish",
  "actors": [
    {
      "name": "Sarah Clarke",
      "imdb": "https://www.imdb.com/name/nm1020124"
    }
  ],
  "bookTitles": [
    "Nine Dragons",
    "The Narrows",
    "Lost Light",
    "Angels Flight",
    "Trunk Music",
    "The Black Echo"
  ]
}
